create table if not exists public.source_snapshots (
  id bigint generated by default as identity primary key,
  source_key text not null,
  data_mode text not null default 'fallback',
  payload jsonb not null default '{}'::jsonb,
  source_refs jsonb not null default '[]'::jsonb,
  warnings jsonb not null default '[]'::jsonb,
  fetched_at timestamptz not null default now()
);

create index if not exists source_snapshots_source_key_fetched_at_idx
  on public.source_snapshots (source_key, fetched_at desc);

create table if not exists public.agent_runs (
  id uuid primary key,
  scenario_id text not null,
  role text not null default 'minister',
  overall_risk int not null default 0,
  mode text not null default 'fallback',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists agent_runs_created_at_idx
  on public.agent_runs (created_at desc);

create table if not exists public.mission_briefs (
  id bigint generated by default as identity primary key,
  agent_run_id uuid references public.agent_runs(id) on delete set null,
  role text not null,
  scenario_id text not null,
  brief jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.source_snapshots enable row level security;
alter table public.agent_runs enable row level security;
alter table public.mission_briefs enable row level security;

drop policy if exists "source snapshots are readable" on public.source_snapshots;
create policy "source snapshots are readable"
  on public.source_snapshots for select using (true);

drop policy if exists "source snapshots insert from anon" on public.source_snapshots;
create policy "source snapshots insert from anon"
  on public.source_snapshots for insert with check (true);

drop policy if exists "agent runs are readable" on public.agent_runs;
create policy "agent runs are readable"
  on public.agent_runs for select using (true);

drop policy if exists "agent runs insert from anon" on public.agent_runs;
create policy "agent runs insert from anon"
  on public.agent_runs for insert with check (true);

drop policy if exists "mission briefs are readable" on public.mission_briefs;
create policy "mission briefs are readable"
  on public.mission_briefs for select using (true);

drop policy if exists "mission briefs insert from anon" on public.mission_briefs;
create policy "mission briefs insert from anon"
  on public.mission_briefs for insert with check (true);

do $$
begin
  alter publication supabase_realtime add table public.agent_runs;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.mission_briefs;
exception
  when duplicate_object then null;
end $$;
